"""
Slices the main COVID-19 case data into time-based CSV files.

This script loads the cleaned ``cases.csv`` file and a list of time
slices defined in the ``SLICES`` variable from ``config.py``.

It then iterates through each slice definition, filters the main DataFrame
to the specified ``start`` and ``end`` dates, and saves the resulting
subset of data to a new CSV file in the ``sliced_data`` output folder.
Files are named sequentially (e.g., ``slice_1.csv``, ``slice_2.csv``).

Notes
-----
This script is intended to be run directly. It depends on the existence of
``cases.csv`` (generated by ``clean_data.py``) and ``config.py``.
"""

import pandas as pd
import os
from config import SLICES

# -----------------------------------
# CONFIGS & LOADING

SLICE_OUTPUT_FOLDER = 'sliced_data'
os.makedirs(SLICE_OUTPUT_FOLDER, exist_ok=True)

try:
    df = pd.read_csv('cases.csv')
    df['date'] = pd.to_datetime(df['date'])
    df = df.sort_values(by='date').set_index('date')
    
    # Optional: calculate the 7-day rolling average so it's included in the output files
    # df['cases_smooth'] = df['cases'].rolling(window=7, center=True).mean()

except Exception as e:
    print(f"Error loading data: {e}")
    exit()

# -----------------------------------

print(f"Saving {len(SLICES)} data slices to the '{SLICE_OUTPUT_FOLDER}' folder...")

slice_number = 0
for slice_data in SLICES:
    start_date = slice_data['start']
    end_date = slice_data['end']
    slice_number = slice_number + 1
    
    # Slice the DataFrame
    df_slice = df.loc[start_date:end_date]
    
    # Create a clean filename
    filename = os.path.join(SLICE_OUTPUT_FOLDER, f'slice_{slice_number}.csv')
    
    # Save to CSV
    df_slice.to_csv(filename)
    print(f"-> Saved: {filename}")

print("\nData slicing complete.")